### ISSUE TITLE
Review - Mozilla Italia l10n da parte dei TS

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/CommunityIssueTracker#24]
Al momento solo io ho cominciato a farlo ma devo finire la lettura.
@gabrycaos @eugeniopetulla @ruphy in attesa della loro revisione.

Risorsa: https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide

**Comment by EugenioPetulla** [comment]
I want propose to integrate footnotes instead of using the ^ char, it's just a little bit of markup (html) but it can help a lot of people in referencing the text in a properly manner.

Eg. of actual notation marks:

This is a text with a note^

^ This is the associated footnote

PoC of what I suggest:

This is a text with a note <sup>[[1]](#footnote1)</sup>

<a name="footnote1">[1]</a>: This is the associated footnote

**Comment by Mte90** [comment]
I will report to @kitsunenosaraT and @gialloporpora that are leading the project.
I have looking to dedicate times to read all the guide and leave my feedback :-)

**Comment by EugenioPetulla** [comment]
I'm also reading this but really I'm not an expert about localization and translation, you know, so I can contribute only improving the readability and the overall User eXperience of the project. :)

**Comment by Mte90** [comment]
Yes of course you know that I speak ```prosciutti``` but a view for devs is asked about also the terms in a way that we use the same in our talks.

**Comment by kitsunenosaraT** [comment]
@EugenioPetulla thank you for your feedback!
You are welcome to write it directly in the [relevant chapter's issue](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/projects/1).

As @Mte90 said, we are interested in your external point of view as a *developer*. 

E.g. When reading translated documentation, is there something that troubles you? For example, terms that has been translated differently from how you are used to? Or terms that are translated *at all*, because you would rather use the English word?

Also, if you had to localize your software or website, what kind of file would you pass to the translator? How would you proceed to put the translated content back in place?

This topics are covered in [Chapter 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) ([Issue](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/issues/27)) and [Chapter 4](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) ([Issue](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/issues/31))

Again, I'm really grateful that you are taking the time to read and comment the guide. For any question feel free to contact me. ~Sara

**Comment by Mte90** [comment]
I done my check on the guide and I think that is great but is missing the part of a glossary (I think that now is easy to udnerstand that I care ti so much).
Few resources can be helpful to add more stuff in the guide:

- https://it.wordpress.org/traduzioni/#reg_gram
- https://translatewiki.net/wiki/FAQ

**Comment by Mte90** [comment]
I think that we close and in case open a new one. This was before the global sprint :-)
