### ISSUE TITLE
Sito - Mozilla Italia Draft

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/CommunityIssueTracker#31]
Waiting for a final draft of the website UI: https://github.com/EugenioPetulla/mozillaitalia.github.io

@eugeniopetulla @gabrycaos

**Comment by EugenioPetulla** [comment]
I'm always ready but we are stuck just because we really don't know what to include in the Website and what not.

Other point is: mozilla.ninja is still at the same initial point, no official fonts and illustrations were released so we have to stay with Arvo instead of using the official Zilla.

Now we have to choose, if you want I can easily speed up the process but I need a well thinked wireframe from you and Edoardo that explains well all the areas you need in the first static version of this website.

@gabrycaos can easily helps me with the functional JS work. :)

**Comment by edovio** [comment]
If all of you prefer we can create a specific project in this repo for the WebSite! :) I see some people involved and is not an activity that concern only Daniele :)

**Comment by Mte90** [comment]
Of course we can start to think again on https://public.etherpad-mozilla.org/p/mozita-sito-2017 about we want to include.
I created the ticket for remember everyone involved :-)

**Comment by EugenioPetulla** [comment]
@edovio yes, you can also fork my repo here in a gh-pages branch so everyone can see live updates

https://github.com/EugenioPetulla/mozillaitalia.github.io

**Comment by edovio** [comment]
Great @EugenioPetulla. So in the next days I create a new Project in this Repo to try to involve more volunteer possible for create a more inclusive way for the new WebSite!!! Great Job and Thank friend! :)
